# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS dev account'
    regionName: 'eu-west-2'
    awsCommand: 'aws sts get-caller-identity'
    failOnStandardError: true
    
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS dev account'
    regionName: 'eu-west-2'
    bucketName: 'app1-dev-artifacts-215097317823'
    sourceFolder: 'examples/no-route53'
    globExpressions: '**'
    targetFolder: 'azuredevops'
    keyManagement: 'awsManaged'
    kmsMasterKeyId: 'arn:aws:kms:eu-west-2:215097317823:key/8cc58888-0f0f-45f3-8e2a-bb977f6b6a8f'
    flattenFolders: true
    logRequest: true
    logResponse: true

